### ISSUE TITLE
Change default labels?

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/.eclipsefdn#42]
Hi all,

we got a more general question it is possible to modificate "Org"-lables with otterdog did not find any related config for labels in the playground.

see https://github.com/eclipse-tractusx/sig-release/discussions/364

**Comment by netomi** [comment]
Currently there is no support for managing labels of a repository via otterdog. Technically its perfectly possible but I was not doing it so far as it would require you to manage the labels via otterdog, which might be too tedious.

One thing that I could imagine that would work is that otterdog does not fully synchronize the labels based on the configuration, but rather makes sure that the ones found in the config are present in the repo. So it will not complain about missing labels in the config, but only ensure that all labels that you have specified are also available live.

That could help to setup a common set of labels for all repos. However, this would have to be done on repo level as there is no concept of organization labels. This could be modelled with a template function for any tractus-x repo, that has a certain set of labels pre-configured.

**Comment by FaGru3n** [comment]
hi @netomi, thanks for the fast input.

My intention maybe to allign with Eclipse Foundation an give them a list with default lables for the organisation and then every new repo with will have theese lables.

and for the already created ones we could use your template idea... to ensure that the config "default" labels are present.

**Comment by netomi** [comment]
I guess you refer to this kind of configuration:

![image](https://github.com/eclipse-tractusx/.eclipsefdn/assets/1048055/d8743828-2316-4d75-9af9-eee8a1029218)

For that config there does not seem to be an api that we can easily access. Otherwise it would be quite reasonable to configure it with otterdog.
