### ISSUE TITLE
Webview diverges from repo config

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/.eclipsefdn#58]
### Current Behavior
Otterdog [repository settings (webview)](https://eclipse-tractusx.github.io/.eclipsefdn/repo-puris/) doesn't reflect the active setup compared to the config:

![grafik](https://github.com/eclipse-tractusx/.eclipsefdn/assets/28647218/2785411e-1f03-4b36-a66f-9524ba16679f)

https://github.com/eclipse-tractusx/.eclipsefdn/blob/61bf6237de8dfad17c9b349acc3a4a16b81e93c5/otterdog/eclipse-tractusx.jsonnet#L719-L721

### Expected Behavior
The webview showing the gh-pages settings correctly.

**Comment by netomi** [comment]
sorry for the delay, that issue got unnoticed for a while, I checked the view and it looks now correct, maybe the action was not running properly for some time.

In any way, the old page is deprecated as it required some GitHub actions to run, please head over to https://otterdog.eclipse.org/projects/automotive.tractusx which should always show the latest config.

We will update the page at https://eclipse-tractusx.github.io/.eclipsefdn/ to point to the new dashboard page.

**Comment by netomi** [comment]
the problem could also be related to caching of content in firefox. I tried to make sure that the pages are not cached, see

```
 <!-- prevent caching -->
  <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0" />
  <meta http-equiv="cache-control" content="max-age=0" />
  <meta http-equiv="expires" content="0" />
  <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
  <meta http-equiv="pragma" content="no-cache" />
```

however i noticed sometimes that I had to do a force-refresh to see the latest content. The dynamic dashboard should not have the problems imho.
